---
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
  # maybe later
  # - repo: https://github.com/pre-commit/mirrors-pylint
    # rev: v2.3.1
    # hooks:
      # - id: pylint
