---
language: python
python: '3.6'
cache:
  yarn: true
  pip: true
  directories:
    - node_modules
before_install:
  - sudo apt-get update
  - nvm install 10
  - nvm use 10
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set restore_free_channel true
  - conda update -q conda
  - conda info -a
install:
  - make setup
script:
  - make test
deploy:
  - provider: npm
    email: reevejamesd@gmail.com
    api_key:
      secure: nTioVM4jtXSJxvsmzmjNRma3O3aZwpgzw41FpmRYXvJVXUknICnkFE0K+4BC6tPAdqLslDfMG34TVsb8jNKgHF14sZfaW9Xnt+HmKv0BQPSQc3WkcUG2E+IJzkEae8KxVM9ikDeeTCnuqgyWRtZTwVdGH/xW8PzYtyL9NzSnWEDmHnsFrgBGC/XSa8uyh5uA3PSSq7epyI9hR+KtiMUhu5woxmPQam0DGzphsU7eUfFT55m+B9Kirg96SyTyPJq7h7c61/30yRSMCtZJ/XGJXEtoQeQXTyp/fnGnl7uylffvky5gD/YgGUU3MYLUX+Zek2zVoButIemicReXnpV0upNTUjJdD0ihufcN1sVp9A03qzde8IMaRxjDOz0PLvgXBLIIAD8jZZwr/xzVDYJ4UMDtlT8gAIb83mXsVto5BkJR0nSHgu/6B3/sEzaV1zWiH/0ZEOCi6FEKJo2AK/wSjtqo37AIrfhw8ntdEC4W+kF72B8be6lMQxc86hdTFkDefCFEMaqZfMEcj4SCgIBCQdVnMaVtmyWS6/Zi1AszP6kWqte7X3awQvSKgYp38wzOuImiXw8rSwi2FdVe5K+u4zE1kBDSL4V1jm1Oy5gf6g+rWESXjzp2CRBzery1ECHoVUlgNIXnru2DLX5Ot/O1iRgBEjQwE6jBFdeRyMeYmRE=
    skip_cleanup: true
    on:
      tags: true
      repo: IBM/jupyterlab-s3-browser
  - provider: pypi
    user: __token__
    password:
      secure: qcTUXuFffUGzabVFk4ju72XptA2lDIDvOtlpVbszbawA/8jamFk/ePeuMqTDLa5GjW41+p5VPD32RXG4xZSStWsXdIWpERWx8dWa22EOBtnkvktXO2q0kVCUqeEHI43XIVafWweT4YyF7i+1Yo0VQyWKGmtYViLCa+NKSTrxxSIsU13hEFnQ1sZ+qIxDUEcBaPvV0nMzFbkaGQ92uH/IzBgtsfu4ps5CAdAXoOcxqG7QBD5ojyHLGyyYL267bSNh66mJazLDDa2bUso7pM8FUDfPgbjJVtOg8HbaRrE5np6FoSV4NAIDOo5zw1uJvw7iyIFjzJXCBp4u/tJMt0SLXNz48rChREDunHiAkyLx3e9Lsspn9Kvvmqgj412WYqG/8LAQpcdUC5LHYKCVa5Xbn1Hm7Xe2hjccAj5bg1iWC7DHNTaUQcwgPipWk2lvqcj82eUiou7Wesi0xsu95Z7zaix9yP6ePSWk+PF20ChVN0gy5Q+lZga541fRzktpme2whLqiVxOln6qgUkZzc50RfOdeN5YgI62Mhd6t6YspCLznaP/FOaA7/yl1KZWFbrc5ydZ0U4QByDcLvqo6mxCW6+7t9HShaEYBZ6eUo3AgJbbiTQhVC85ct0mlTP+jq7AVrTUM8kMRDnXTsNeJ/AN90fzOoFwrythq9rgrAuW2/ME=
    skip_cleanup: true
    on:
      tags: true
      repo: IBM/jupyterlab-s3-browser
